In [75]:
import numpy as np
data = np.loadtxt('2018nba.csv', delimiter=',', usecols=(7,8,9,10,21))

In [76]:
data

array([[25. , 35.7,  6.4,  8.3,  1. ],
       [20. , 29.3, 13.3,  4.4,  1. ],
       [28. , 29.3,  5.2,  5.6,  1. ],
       ...,
       [ 1. ,  0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ,  0. ]])

In [77]:
X = data[:,0:4]
Y = data[:,4]

In [78]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='newton-cg', penalty='none')
model.fit(X, Y)

model.coef_

array([[0.10958996, 0.32531141, 0.20496524, 0.40854394]])

In [79]:
model.intercept_

array([-12.98307602])

In [49]:
model.score(X, Y)

0.9774590163934426

In [59]:
X = np.hstack((np.ones((488,1)), data[:,0:4], data[:,1:2]**2,data[:,1:2]**3))

In [60]:
beta = np.linalg.inv(X.T@X)@X.T@Y
s2 = (Y-X@beta).T @ (Y-X@beta) / (488-7)

In [62]:
beta

array([ 4.13432206e-02,  2.69922844e-03, -4.20771539e-02,  1.25059134e-02,
        2.51360516e-02,  2.10862869e-03,  1.41920321e-06])

In [63]:
s2

0.024108031047212777

In [65]:
X = np.hstack((np.ones((488,1)),data[:,0:4]))
Y = data[:,4]

In [66]:
beta = np.linalg.inv(X.T@X)@X.T@Y
mu = X @ beta
e = Y - mu
s2 = e.T @ e / (488-5)

In [67]:
import scipy.stats as st
T = (mu.T@mu - 488*np.mean(Y)**2 ) /(5-1) /s2
p = 1-st.f.cdf(T, 5-1, 488-5)

In [68]:
p

1.1102230246251565e-16

In [70]:
Y = data[:,4]
X = np.hstack(( np.ones((488,1)), data[:,0:1] ))
beta = np.linalg.inv(X.T@X)@X.T@Y
488 * np.log( (Y-X@beta).T@(Y-X@beta)/488 ) + 2*(2)

-1467.9832268760606

In [72]:
X = np.hstack(( np.ones((488,1)), data[:,1:2] ))
beta = np.linalg.inv(X.T@X)@X.T@Y
488 * np.log( (Y-X@beta).T@(Y-X@beta)/488 ) + 2*(2)

-1608.4757432145036

In [73]:
X = np.hstack(( np.ones((488,1)), data[:,0:2] ))
beta = np.linalg.inv(X.T@X)@X.T@Y
488 * np.log( (Y-X@beta).T@(Y-X@beta)/488 ) + 2*(3)

-1606.8448004175168

In [74]:
X = np.ones((488,1))
beta = np.linalg.inv(X.T@X)@X.T@Y
488 * np.log( (Y-X@beta).T@(Y-X@beta)/488 ) + 2*(1)

-1438.2812005201947

In [89]:
Lebron = np.array([[41,25,7.8,10.8]])

In [90]:
model.predict_proba(Lebron)

array([[0.00349159, 0.99650841]])

In [93]:
Rudy = np.array([[35,15.6,14.6,1.5]])

In [94]:
model.predict_proba(Rudy)

array([[0.61473524, 0.38526476]])